kind: ResourceQuota
apiVersion: v1
metadata:
  name: backend-quota
  annotations:
    configmanagement.gke.io/cluster-selector: select-env-prod
spec:
  hard:
    pods: "3"
    cpu: "1"
    memory: 1Gi
